# Generated by Django 6.0.2 on 2026-03-13 00:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Продукт')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='Марка')),
                ('unit', models.CharField(choices=[('g', 'Грамове (g)'), ('pcs', 'Опаковка (бр.)')], max_length=10, verbose_name='Мерна единица')),
                ('calories_per_100', models.PositiveIntegerField(default=0, verbose_name='Калории / 100g')),
                ('protein_per_100', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Белтъчини / 100g')),
                ('carbs_per_100', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Въглехидрати / 100g')),
                ('fat_per_100', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Мазнини / 100g')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Цена за килограм или опаковка', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('is_basic', models.BooleanField(default=False, help_text='Продукт, от който винаги трябва да има наличност.', verbose_name='Основен продукт')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Магазин')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Налично количество')),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимално количество')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.product', verbose_name='Продукт')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.store', verbose_name='Магазин'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'brand')},
        ),
    ]
