# Generated by Django 6.0.2 on 2026-03-13 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True, verbose_name='Начален ден от седмицата')),
                ('notes', models.TextField(blank=True, verbose_name='Бележки')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Понеделник'), (2, 'Вторник'), (3, 'Сряда'), (4, 'Четвъртък'), (5, 'Петък'), (6, 'Събота'), (7, 'Неделя')], verbose_name='Ден')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Закуска'), ('lunch', 'Обяд'), ('snack', 'Междинно хранене'), ('dinner', 'Вечеря')], max_length=20, verbose_name='Хранене')),
                ('eating_out', models.BooleanField(default=False, verbose_name='Хранене навън')),
                ('notes', models.TextField(blank=True, verbose_name='Бележки')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.dish', verbose_name='Ястие')),
                ('week_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='weekmenu.weekmenu')),
            ],
            options={
                'unique_together': {('week_menu', 'day', 'meal_type')},
            },
        ),
    ]
